### PR TITLE
Add my octocat (filename should work this time)

### PR DESCRIPTION
**Pull request by frosetrain**
## ✅ Checks

- [x] This PR contains one and one image only
- [x] I pledge solemnly that i put in a appropriate picture
- [x] My picture is formatted in <name> octocat

### CODE REVIEW

**Comment by frosetrain** [comment]
me after accidentally making people using windows not able to clone

**Review by saumilthecode — CHANGES_REQUESTED** [review]
linus we've been over this please remove spaces we wish not for another purgatory

**Review by TwelvePenguins — COMMENTED** [review]
Linus there should be no spacing. I wish not to be the United Nations and send a sternly worded warning letter to your administration.

**Comment by frosetrain** [comment]
that was caused by a newline, not space. space is fine. but anyways here ya go.

**Comment by frosetrain** [comment]
saumil's octocat.png has been here the whole time with a space

**Comment by TwelvePenguins** [comment]
mb cuhlinus skull skull skull

**Comment by saumilthecode** [comment]
thank you linus

**Comment by frosetrain** [comment]
sorry again for the initial oopsie

**Comment by saumilthecode** [comment]
oops how did you manage to newline in the first place 💀

**Review by saumilthecode — APPROVED** [review]
lgtm

**Comment by frosetrain** [comment]
on linux terminal

**Comment by TwelvePenguins** [comment]
saumils octocat is special

**Comment by saumilthecode** [comment]
peak linux moment

**Comment by frosetrain** [comment]
when you write " then press enter, the command isn't run, the next line becomes part of the previous one

**Pull request merged**
