### PR TITLE
add octocat

### PR DESCRIPTION
**Pull request by carrotpgk222**
## ✅ Checks

[] This PR contains one and one image only
[] I pledge solemnly that i put in a appropriate picture
[] My picture is formatted in <name> octocat

### CODE REVIEW

**Review by saumilthecode — CHANGES_REQUESTED** [review]
lgtm

**Comment by true-Grand** [comment]
> lgtm

what @saumilthecode

**Comment by saumilthecode** [comment]
Oh skull wrong button

**Comment by saumilthecode** [comment]
Ion know how to approve on mobile I'll approve tmr mornin

**Review by saumilthecode — APPROVED** [review]
lgtm

**Pull request merged**
