### PR TITLE
add octocat

### PR DESCRIPTION
**Pull request by Guanyou02**
## ✅ Checks

- [x] This PR contains one and one image only
- [x] I pledge solemnly that I put in an appropriate picture
- [x] My picture is formatted in guanyou's-octocat.png

### CODE REVIEW

**Comment by frosetrain** [comment]
LGTM

**Comment by true-Grand** [comment]
Remove your spacing with a dash

**Comment by frosetrain** [comment]
@true-Grand spaces are fine right, newlines are not

**Comment by saumilthecode** [comment]
we dont wish to take on any more risks unfortunately :(

**Comment by saumilthecode** [comment]
pls rename

**Review by saumilthecode — CHANGES_REQUESTED** [review]
rename pls

**Comment by Guanyou02** [comment]
I renamed it

**Comment by saumilthecode** [comment]
pls rename from "guanyou's octocat.png" to "guanyou's-octocat.png"

**Comment by saumilthecode** [comment]
we wish not for any unfortunate conflicts :D

**Comment by Guanyou02** [comment]
got it!

**Comment by saumilthecode** [comment]
actually nvm ill merge myself n change

**Review by saumilthecode — APPROVED** [review]
lftm

**Comment by frosetrain** [comment]
merged 1 day after the workshop?

**Comment by saumilthecode** [comment]
Yea I was waiting on the original pr'er's changes but realised I could just merge it in then change since any breaking changes shouldn't affect anyone anymore lol

**Pull request merged**
