### PR TITLE
i would like to add my great penguin

### PR DESCRIPTION
**Pull request by saumilthecode**
## ✅ Checks

[x] This PR contains one and one image only
[x] I pledge solemnly that i put in a appropriate picture
[] My picture is formatted in <name> octocat (no)

### CODE REVIEW

**Comment by saumilthecode** [comment]
wonder if this automerges

**Comment by saumilthecode** [comment]
why cant i request my own review 👎

**Comment by true-Grand** [comment]
Merged

**Review by true-Grand — APPROVED** [review]
Lovely photo!

**Pull request merged**
